name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for contribution data

      - name: Create assets directory
        run: mkdir -p dist  # Using 'dist' instead of 'assets'

      - uses: Platane/snk@v2
        id: snake
        with:
          github_user_name: lestonEth
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Uncomment for dark theme:
          # theme: dark
          # svg_out_path: dist/github-contribution-grid-snake-dark.svg

      - name: Verify SVG generation
        run: |
          ls -la dist/
          [ -f dist/github-contribution-grid-snake.svg ] || exit 1

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output  # This branch must exist
          keep_files: false
